import CryptoKit
import Foundation

/// 剪贴板历史的一条记录。图片只存文件名，正文不进待办库。
struct ClipboardHistoryRecord: Codable, Equatable, Identifiable, Sendable {
    var id: UUID
    var copiedAt: Date
    var pinnedAt: Date?
    /// 置顶后固定的小写字母。列表重排不改它；取消置顶就释放。
    var pinKey: String?
    var sourceBundleID: String
    var plainText: String
    var html: String?
    var rtf: Data?
    var imageFile: String?
    /// 复制文件时记下的路径。粘贴时写回文件 URL，不把文件字节收进历史。
    var filePaths: [String]
    var contentHash: String

    var isPinned: Bool { pinnedAt != nil }

    private enum CodingKeys: String, CodingKey {
        case id, copiedAt, pinnedAt, pinKey, sourceBundleID, plainText, html, rtf, imageFile, filePaths, contentHash
    }

    init(
        id: UUID,
        copiedAt: Date,
        pinnedAt: Date?,
        pinKey: String? = nil,
        sourceBundleID: String,
        plainText: String,
        html: String?,
        rtf: Data?,
        imageFile: String?,
        filePaths: [String] = [],
        contentHash: String
    ) {
        self.id = id
        self.copiedAt = copiedAt
        self.pinnedAt = pinnedAt
        self.pinKey = pinKey
        self.sourceBundleID = sourceBundleID
        self.plainText = plainText
        self.html = html
        self.rtf = rtf
        self.imageFile = imageFile
        self.filePaths = filePaths
        self.contentHash = contentHash
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        copiedAt = try container.decode(Date.self, forKey: .copiedAt)
        pinnedAt = try container.decodeIfPresent(Date.self, forKey: .pinnedAt)
        pinKey = try container.decodeIfPresent(String.self, forKey: .pinKey)
        sourceBundleID = try container.decode(String.self, forKey: .sourceBundleID)
        plainText = try container.decode(String.self, forKey: .plainText)
        html = try container.decodeIfPresent(String.self, forKey: .html)
        rtf = try container.decodeIfPresent(Data.self, forKey: .rtf)
        imageFile = try container.decodeIfPresent(String.self, forKey: .imageFile)
        filePaths = try container.decodeIfPresent([String].self, forKey: .filePaths) ?? []
        contentHash = try container.decode(String.self, forKey: .contentHash)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(copiedAt, forKey: .copiedAt)
        try container.encodeIfPresent(pinnedAt, forKey: .pinnedAt)
        try container.encodeIfPresent(pinKey, forKey: .pinKey)
        try container.encode(sourceBundleID, forKey: .sourceBundleID)
        try container.encode(plainText, forKey: .plainText)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(rtf, forKey: .rtf)
        try container.encodeIfPresent(imageFile, forKey: .imageFile)
        try container.encode(filePaths, forKey: .filePaths)
        try container.encode(contentHash, forKey: .contentHash)
    }

    var preview: String {
        let flattened = plainText.replacingOccurrences(of: "\n", with: " ")
        let trimmed = flattened.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > 180 else { return trimmed }
        return String(trimmed.prefix(180))
    }
}

enum ClipboardSearchMode: String, Codable, CaseIterable, Sendable {
    case mixed
    case exact
    case regex
}

enum ClipboardPanelAnchor: String, Codable, CaseIterable, Sendable {
    case cursor
    case center
}

enum ClipboardClickAction: String, Codable, CaseIterable, Sendable {
    case copy
    case paste
}

/// 从剪贴板读出、尚未决定是否收录的草稿。
struct ClipboardHistoryDraft: Equatable, Sendable {
    var plainText: String
    var html: String?
    var rtf: Data?
    var png: Data?
    var filePaths: [String] = []
    var types: Set<String>
    var sourceBundleID: String
    var copiedAt: Date
}

enum ClipboardHistoryRules {
    static let markerType = "org.areachain.clipboard.history"
    /// 密码管理器和系统临时剪贴板。这些类型始终忽略，不能在设置里关掉。
    static let sealedTypes: Set<String> = [
        markerType,
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb"
    ]
    static let universalClipboardType = "com.apple.is-remote-clipboard"
    static let defaultLimit = 200
    static let minimumLimit = 20
    static let maximumLimit = 999
    static let maximumPayloadBytes = 2_000_000
    static let defaultInterval: TimeInterval = 0.5
    static let minimumInterval: TimeInterval = 0.1
    static let maximumInterval: TimeInterval = 2
    static let pinAlphabet = "abcdefghijklmnopqrstuvwxyz"

    static func clampLimit(_ value: Int) -> Int {
        min(maximumLimit, max(minimumLimit, value))
    }

    static func clampInterval(_ value: TimeInterval) -> TimeInterval {
        min(maximumInterval, max(minimumInterval, value))
    }

    static func isValidPattern(_ pattern: String) -> Bool {
        let trimmed = pattern.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        return (try? NSRegularExpression(pattern: trimmed)) != nil
    }

    /// 过大的图片或富文本丢掉，只保留还能搜索的纯文本。什么都不剩就返回 nil。
    static func record(
        from draft: ClipboardHistoryDraft,
        ignoredApps: Set<String>,
        extraTypes: Set<String>,
        patterns: [String],
        ignoreUniversal: Bool,
        id: UUID = UUID()
    ) -> ClipboardHistoryRecord? {
        guard !shouldIgnore(
            types: draft.types,
            bundleID: draft.sourceBundleID,
            plainText: draft.plainText,
            ignoredApps: ignoredApps,
            extraTypes: extraTypes,
            patterns: patterns,
            ignoreUniversal: ignoreUniversal
        ) else { return nil }

        var plain = draft.plainText
        var html = draft.html
        var rtf = draft.rtf
        var png = draft.png
        if (png?.count ?? 0) > maximumPayloadBytes { png = nil }
        if (rtf?.count ?? 0) > maximumPayloadBytes { rtf = nil }
        if plain.utf8.count > maximumPayloadBytes {
            plain = String(plain.prefix(100_000))
        }
        let trimmed = plain.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty && png == nil && rtf == nil && (html?.isEmpty != false) {
            return nil
        }
        if trimmed.isEmpty { html = nil }
        let paths = draft.filePaths
        return ClipboardHistoryRecord(
            id: id,
            copiedAt: draft.copiedAt,
            pinnedAt: nil,
            sourceBundleID: draft.sourceBundleID,
            plainText: plain,
            html: html,
            rtf: rtf,
            imageFile: nil,
            filePaths: paths,
            contentHash: digest(plain: plain, html: html, rtf: rtf, png: png, filePaths: paths)
        )
    }

    static func shouldIgnore(
        types: Set<String>,
        bundleID: String,
        plainText: String,
        ignoredApps: Set<String>,
        extraTypes: Set<String>,
        patterns: [String],
        ignoreUniversal: Bool
    ) -> Bool {
        if !types.isDisjoint(with: sealedTypes) { return true }
        if !types.isDisjoint(with: extraTypes) { return true }
        if ignoreUniversal && types.contains(universalClipboardType) { return true }
        if !bundleID.isEmpty && ignoredApps.contains(bundleID) { return true }
        for pattern in patterns where isValidPattern(pattern) {
            guard let expression = try? NSRegularExpression(pattern: pattern) else { continue }
            let range = NSRange(plainText.startIndex..., in: plainText)
            if expression.firstMatch(in: plainText, range: range) != nil { return true }
        }
        return false
    }

    static func ordered(_ items: [ClipboardHistoryRecord]) -> [ClipboardHistoryRecord] {
        items.sorted { lhs, rhs in
            switch (lhs.pinnedAt, rhs.pinnedAt) {
            case let (left?, right?):
                if left != right { return left < right }
                return lhs.copiedAt > rhs.copiedAt
            case (.some, .none):
                return true
            case (.none, .some):
                return false
            case (.none, .none):
                if lhs.copiedAt != rhs.copiedAt { return lhs.copiedAt > rhs.copiedAt }
                return lhs.id.uuidString < rhs.id.uuidString
            }
        }
    }

    static func filtered(
        _ items: [ClipboardHistoryRecord],
        query: String,
        mode: ClipboardSearchMode
    ) -> [ClipboardHistoryRecord] {
        let matching = ClipboardTextMatching(needle: query, mode: mode)
        return ordered(items).filter { matching.matches($0.plainText) }
    }

    static func merging(
        _ items: [ClipboardHistoryRecord],
        new: ClipboardHistoryRecord,
        limit: Int
    ) -> [ClipboardHistoryRecord] {
        var next = items
        if let index = next.firstIndex(where: { $0.contentHash == new.contentHash && !new.contentHash.isEmpty }) {
            var existing = next.remove(at: index)
            existing.copiedAt = new.copiedAt
            existing.plainText = new.plainText
            existing.html = new.html
            existing.rtf = new.rtf
            if let imageFile = new.imageFile { existing.imageFile = imageFile }
            if !new.filePaths.isEmpty { existing.filePaths = new.filePaths }
            if !new.sourceBundleID.isEmpty { existing.sourceBundleID = new.sourceBundleID }
            next.append(existing)
        } else {
            next.append(new)
        }
        return trimming(next, limit: clampLimit(limit))
    }

    static func pin(_ items: [ClipboardHistoryRecord], id: UUID, at date: Date) -> [ClipboardHistoryRecord] {
        let used = Set(items.compactMap(\.pinKey))
        let assigned = nextPinKey(used: used)
        return items.map { item in
            guard item.id == id else { return item }
            var copy = item
            if copy.pinnedAt == nil { copy.pinnedAt = date }
            if copy.pinKey == nil { copy.pinKey = assigned }
            return copy
        }
    }

    static func unpin(_ items: [ClipboardHistoryRecord], id: UUID) -> [ClipboardHistoryRecord] {
        items.map { item in
            guard item.id == id else { return item }
            var copy = item
            copy.pinnedAt = nil
            copy.pinKey = nil
            return copy
        }
    }

    static func nextPinKey(used: Set<String>) -> String? {
        pinAlphabet.first { !used.contains(String($0)) }.map(String.init)
    }

    static func removing(_ items: [ClipboardHistoryRecord], id: UUID) -> [ClipboardHistoryRecord] {
        items.filter { $0.id != id }
    }

    static func clearing(_ items: [ClipboardHistoryRecord], includingPinned: Bool) -> [ClipboardHistoryRecord] {
        includingPinned ? [] : items.filter(\.isPinned)
    }

    /// 置顶项不占名额，避免清空上限时把钉住的模板删掉。
    static func trimming(_ items: [ClipboardHistoryRecord], limit: Int) -> [ClipboardHistoryRecord] {
        let cap = clampLimit(limit)
        let pinned = ordered(items).filter(\.isPinned)
        let unpinned = ordered(items).filter { !$0.isPinned }.prefix(cap)
        return pinned + unpinned
    }

    static func digest(plain: String, html: String?, rtf: Data?, png: Data?, filePaths: [String] = []) -> String {
        var hasher = SHA256()
        hasher.update(data: Data(plain.utf8))
        hasher.update(data: Data((html ?? "").utf8))
        hasher.update(data: rtf ?? Data())
        hasher.update(data: png ?? Data())
        hasher.update(data: Data(filePaths.joined(separator: "\n").utf8))
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    /// 混合模式按字符顺序模糊匹配，因此「cta」也能命中「catalog」。
    static func highlightRanges(in text: String, needle: String, mode: ClipboardSearchMode) -> [Range<String.Index>] {
        ClipboardTextMatching(needle: needle, mode: mode).ranges(in: text)
    }
}
